package com.yupi.yuaiagent.task.agent.impl;

import cn.hutool.core.io.FileUtil;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yupi.yuaiagent.task.agent.Agent;
import com.yupi.yuaiagent.task.agent.AgentContext;
import com.yupi.yuaiagent.task.agent.AgentResult;
import com.yupi.yuaiagent.task.agent.AgentStepSummary;
import com.yupi.yuaiagent.task.agent.NextAction;
import com.yupi.yuaiagent.task.dto.CodeFlowStepDto;
import com.yupi.yuaiagent.task.dto.CodeModuleDto;
import com.yupi.yuaiagent.task.dto.EvidenceRefDto;
import com.yupi.yuaiagent.task.dto.ModuleSummaryOutputDto;
import com.yupi.yuaiagent.task.dto.RootCauseHypothesisDto;
import com.yupi.yuaiagent.task.dto.RootCauseReportDto;
import com.yupi.yuaiagent.task.entity.AgentTask;
import com.yupi.yuaiagent.task.repository.AgentTaskRepository;
import com.yupi.yuaiagent.task.service.AgentArtifactService;
import com.yupi.yuaiagent.task.service.AgentTaskWorkspaceService;
import jakarta.persistence.EntityNotFoundException;
import org.springframework.stereotype.Component;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Component
public class DeliveryAgent implements Agent {

    private final AgentTaskRepository agentTaskRepository;
    private final AgentTaskWorkspaceService agentTaskWorkspaceService;
    private final AgentArtifactService agentArtifactService;
    private final ObjectMapper objectMapper;

    public DeliveryAgent(AgentTaskRepository agentTaskRepository,
                         AgentTaskWorkspaceService agentTaskWorkspaceService,
                         AgentArtifactService agentArtifactService,
                         ObjectMapper objectMapper) {
        this.agentTaskRepository = agentTaskRepository;
        this.agentTaskWorkspaceService = agentTaskWorkspaceService;
        this.agentArtifactService = agentArtifactService;
        this.objectMapper = objectMapper;
    }

    @Override
    public String name() {
        return "DeliveryAgent";
    }

    @Override
    public AgentResult run(AgentContext context) {
        AgentTask task = agentTaskRepository.findById(context.getTaskId())
                .orElseThrow(() -> new EntityNotFoundException("Task not found: " + context.getTaskId()));
        return "CODE_UNDERSTANDING".equalsIgnoreCase(context.getBusinessType())
                ? deliverModuleSummary(task, context)
                : deliverDiagnosis(task, context);
    }

    private AgentResult deliverModuleSummary(AgentTask task, AgentContext context) {
        AgentStepSummary understandingStep = context.getPreviousSteps().stream()
                .filter(step -> "CodeUnderstandingAgent".equals(step.getAssignedAgent()))
                .reduce((first, second) -> second)
                .orElse(null);
        List<EvidenceRefDto> evidenceRefs = context.getEvidenceRefs() == null ? List.of() : context.getEvidenceRefs();
        if (understandingStep == null || evidenceRefs.isEmpty()) {
            return AgentResult.builder()
                    .success(false)
                    .summary("Delivery cannot produce the module summary because grounded code evidence is missing.")
                    .structuredOutput(Map.of())
                    .evidenceRefs(evidenceRefs)
                    .confidence(0.1D)
                    .nextAction(NextAction.FAIL)
                    .failureReason("DeliveryAgent requires code understanding output and evidence refs.")
                    .build();
        }

        ModuleSummaryOutputDto summary = toModuleSummary(understandingStep);
        File moduleSummaryFile = agentTaskWorkspaceService.resolveWorkspaceFile(task, "artifacts/module-summary.json");
        FileUtil.writeString(writePrettyJson(summary), moduleSummaryFile, StandardCharsets.UTF_8);
        File codeEvidenceFile = agentTaskWorkspaceService.resolveWorkspaceFile(task, "artifacts/code-evidence.json");
        FileUtil.writeString(writePrettyJson(Map.of("evidenceRefs", evidenceRefs)), codeEvidenceFile, StandardCharsets.UTF_8);

        agentArtifactService.upsertModuleSummaryArtifact(
                task.getId(),
                context.getStepId(),
                "module-summary.json",
                "artifacts/module-summary.json",
                "Structured code understanding artifact generated by DeliveryAgent.",
                summary,
                evidenceRefs,
                moduleSummaryFile
        );
        agentArtifactService.upsertCodeEvidenceArtifact(
                task.getId(),
                context.getStepId(),
                "code-evidence.json",
                "artifacts/code-evidence.json",
                "Collected code evidence used by the code understanding workflow.",
                Map.of("evidenceRefs", evidenceRefs),
                evidenceRefs,
                codeEvidenceFile
        );

        Map<String, Object> deliverableOutput = new LinkedHashMap<>();
        deliverableOutput.put("moduleSummaryArtifact", "artifacts/module-summary.json");
        deliverableOutput.put("codeEvidenceArtifact", "artifacts/code-evidence.json");
        deliverableOutput.put("deliveryMode", summary.getDeliveryMode());
        deliverableOutput.put("partial", summary.getPartial());
        deliverableOutput.put("missingInfo", summary.getMissingInfo());
        deliverableOutput.put("suggestedFollowUpQueries", summary.getSuggestedFollowUpQueries());

        return AgentResult.builder()
                .success(true)
                .summary(summary.getSummary())
                .structuredOutput(deliverableOutput)
                .evidenceRefs(evidenceRefs)
                .confidence(0.92D)
                .nextAction(NextAction.DELIVER)
                .failureReason(null)
                .build();
    }

    private AgentResult deliverDiagnosis(AgentTask task, AgentContext context) {
        AgentStepSummary diagnosisStep = context.getPreviousSteps().stream()
                .filter(step -> "DiagnosisAgent".equals(step.getAssignedAgent()))
                .reduce((first, second) -> second)
                .orElse(null);
        AgentStepSummary patchStep = context.getPreviousSteps().stream()
                .filter(step -> "PatchAgent".equals(step.getAssignedAgent()))
                .reduce((first, second) -> second)
                .orElse(null);
        List<EvidenceRefDto> evidenceRefs = context.getEvidenceRefs() == null ? List.of() : context.getEvidenceRefs();
        if (diagnosisStep == null || evidenceRefs.isEmpty()) {
            return AgentResult.builder()
                    .success(false)
                    .summary("Delivery cannot produce the final report because diagnosis evidence is missing.")
                    .structuredOutput(Map.of())
                    .evidenceRefs(evidenceRefs)
                    .confidence(0.1D)
                    .nextAction(NextAction.FAIL)
                    .failureReason("DeliveryAgent requires diagnosis output and evidence refs.")
                    .build();
        }

        RootCauseReportDto report = RootCauseReportDto.builder()
                .summary(diagnosisStep.getSummary())
                .hypotheses(toHypotheses(diagnosisStep))
                .risk(readString(diagnosisStep.getStructuredOutput(), "risk",
                        "Please verify the highlighted code paths with runtime logs before applying a fix."))
                .nextSteps(readList(diagnosisStep.getStructuredOutput(), "nextSteps",
                        List.of("Confirm the suspected code path", "Prepare a small reproduction or regression test")))
                .build();

        File rootCauseFile = agentTaskWorkspaceService.resolveWorkspaceFile(task, "artifacts/root-cause-report.json");
        FileUtil.writeString(writePrettyJson(report), rootCauseFile, StandardCharsets.UTF_8);
        File codeEvidenceFile = agentTaskWorkspaceService.resolveWorkspaceFile(task, "artifacts/code-evidence.json");
        FileUtil.writeString(writePrettyJson(Map.of("evidenceRefs", evidenceRefs)), codeEvidenceFile, StandardCharsets.UTF_8);

        agentArtifactService.upsertRootCauseReportArtifact(
                task.getId(),
                context.getStepId(),
                "root-cause-report.json",
                "artifacts/root-cause-report.json",
                "Structured root cause report generated by DeliveryAgent.",
                report,
                evidenceRefs,
                rootCauseFile
        );
        agentArtifactService.upsertCodeEvidenceArtifact(
                task.getId(),
                context.getStepId(),
                "code-evidence.json",
                "artifacts/code-evidence.json",
                "Collected code evidence used by the diagnosis workflow.",
                Map.of("evidenceRefs", evidenceRefs),
                evidenceRefs,
                codeEvidenceFile
        );

        String finalSummary = patchStep == null
                ? report.getSummary()
                : readString(patchStep.getStructuredOutput(), "patchPlan", report.getSummary());
        Map<String, Object> deliverableOutput = new LinkedHashMap<>();
        deliverableOutput.put("rootCauseArtifact", "artifacts/root-cause-report.json");
        deliverableOutput.put("codeEvidenceArtifact", "artifacts/code-evidence.json");
        if (patchStep != null) {
            deliverableOutput.put("patchPlanArtifact", "artifacts/patch-plan.json");
        }

        return AgentResult.builder()
                .success(true)
                .summary(finalSummary)
                .structuredOutput(deliverableOutput)
                .evidenceRefs(evidenceRefs)
                .confidence(0.92D)
                .nextAction(NextAction.DELIVER)
                .failureReason(null)
                .build();
    }

    @SuppressWarnings("unchecked")
    private ModuleSummaryOutputDto toModuleSummary(AgentStepSummary understandingStep) {
        Map<String, Object> output = understandingStep.getStructuredOutput();
        Object rawModules = output == null ? null : output.get("modules");
        List<CodeModuleDto> modules = rawModules instanceof List<?>
                ? ((List<?>) rawModules).stream()
                .filter(Map.class::isInstance)
                .map(Map.class::cast)
                .map(item -> CodeModuleDto.builder()
                        .name(readString(item, "name", "Unnamed module"))
                        .responsibility(readString(item, "responsibility", "Responsibility was not specified."))
                        .evidence(readList(item, "evidence", List.of()))
                        .keyFiles(readList(item, "keyFiles", List.of()))
                        .build())
                .toList()
                : List.of();
        return ModuleSummaryOutputDto.builder()
                .intent(readString(output, "intent", "OVERALL_STRUCTURE"))
                .targetModule(readString(output, "targetModule", null))
                .subType(readString(output, "subType", "MODULE_SUMMARY"))
                .outputSchema(readString(output, "outputSchema", readString(output, "subType", "MODULE_SUMMARY")))
                .deliveryMode(readString(output, "deliveryMode", "FINAL"))
                .summary(readString(output, "summary", understandingStep.getSummary()))
                .modules(modules)
                .flowSteps(toFlowSteps(output))
                .operations(readObjectList(output, "operations"))
                .callChain(readObjectList(output, "callChain"))
                .architectureNotes(readList(output, "architectureNotes",
                        List.of("Review the cited files to refine the architecture summary further.")))
                .riskNotes(readList(output, "riskNotes", List.of()))
                .notesAndRisks(readList(output, "notesAndRisks", List.of()))
                .needMoreSearch(Boolean.TRUE.equals(output == null ? null : output.get("needMoreSearch")))
                .partial(Boolean.TRUE.equals(output == null ? null : output.get("partial")))
                .confirmedScope(readList(output, "confirmedScope", List.of()))
                .missingInfo(readList(output, "missingInfo", List.of()))
                .suggestedFollowUpQueries(readList(output, "suggestedFollowUpQueries", List.of()))
                .build();
    }

    @SuppressWarnings("unchecked")
    private List<CodeFlowStepDto> toFlowSteps(Map<String, Object> output) {
        Object rawFlowSteps = output == null ? null : output.get("flowSteps");
        if (!(rawFlowSteps instanceof List<?> rawList)) {
            return List.of();
        }
        return rawList.stream()
                .filter(Map.class::isInstance)
                .map(Map.class::cast)
                .map(item -> CodeFlowStepDto.builder()
                        .step(readString(item, "step", "Unspecified step"))
                        .description(readString(item, "description", "Description was not specified."))
                        .evidence(readList(item, "evidence", List.of()))
                        .keyFiles(readList(item, "keyFiles", List.of()))
                        .build())
                .toList();
    }

    @SuppressWarnings("unchecked")
    private List<Map<String, Object>> readObjectList(Map<String, Object> output, String key) {
        Object value = output == null ? null : output.get(key);
        if (!(value instanceof List<?> rawList)) {
            return List.of();
        }
        return rawList.stream()
                .filter(Map.class::isInstance)
                .map(item -> (Map<String, Object>) item)
                .toList();
    }

    @SuppressWarnings("unchecked")
    private List<RootCauseHypothesisDto> toHypotheses(AgentStepSummary diagnosisStep) {
        Object rawHypotheses = diagnosisStep.getStructuredOutput() == null ? null : diagnosisStep.getStructuredOutput().get("hypotheses");
        if (rawHypotheses instanceof List<?> hypotheses) {
            return hypotheses.stream()
                    .filter(Map.class::isInstance)
                    .map(Map.class::cast)
                    .map(item -> RootCauseHypothesisDto.builder()
                            .cause(readString(item, "cause", "Potential code path issue"))
                            .evidence(readList(item, "evidence", List.of()))
                            .confidence(readDouble(item, "confidence", diagnosisStep.getConfidence()))
                            .build())
                    .toList();
        }
        return List.of(RootCauseHypothesisDto.builder()
                .cause(diagnosisStep.getSummary())
                .evidence(List.of())
                .confidence(diagnosisStep.getConfidence())
                .build());
    }

    private String readString(Map<String, Object> map, String key, String defaultValue) {
        if (map == null) {
            return defaultValue;
        }
        Object value = map.get(key);
        return value == null ? defaultValue : String.valueOf(value);
    }

    @SuppressWarnings("unchecked")
    private List<String> readList(Map<String, Object> map, String key, List<String> defaultValue) {
        if (map == null) {
            return defaultValue;
        }
        Object value = map.get(key);
        if (value instanceof List<?> list) {
            return list.stream().map(String::valueOf).toList();
        }
        return defaultValue;
    }

    private Double readDouble(Map<String, Object> map, String key, Double defaultValue) {
        if (map == null) {
            return defaultValue;
        }
        Object value = map.get(key);
        if (value instanceof Number number) {
            return number.doubleValue();
        }
        return defaultValue;
    }

    private String writePrettyJson(Object value) {
        try {
            return objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(value);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to serialize delivery artifact.", e);
        }
    }
}
